# Fly.io configuration for FreeSWITCH Lab - NestJS App
# This deploys only the backend API service
# Note: FreeSWITCH and security-agent require a VPS with host networking

app = 'freeswitch-lab-app'  # Change this to your desired app name
primary_region = 'sin'  # Change to your preferred region (sin=Singapore, iad=US East, etc.)

[build]
  dockerfile = "docker/app.Dockerfile"

[env]
  NODE_ENV = "production"
  APP_PORT = "3000"
  TZ = "Asia/Ho_Chi_Minh"
  DB_PORT = "3306"
  DB_USER = "fsapp"
  DB_NAME = "freeswitch"
  DB_LOGGING = "false"
  DB_SYNC = "true"
  SEED_DEMO_DATA = "false"  # Set to true only for initial deployment
  FS_ESL_PORT = "8021"
  RECORDINGS_DIR = "/recordings"
  SECURITY_AGENT_TIMEOUT_MS = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Scale to zero when idle

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "recordings"
  destination = "/recordings"

# You'll need to set these secrets using:
# fly secrets set DB_HOST=your-mysql-host
# fly secrets set DB_PASSWORD=your-db-password
# fly secrets set PORTAL_JWT_SECRET=your-secret-key
# fly secrets set PORTAL_ADMIN_PASSWORD=your-admin-password
# fly secrets set FS_ESL_HOST=your-freeswitch-host (if using external FS)
# fly secrets set FS_ESL_PASSWORD=ClueCon
# fly secrets set SECURITY_AGENT_URL=http://your-agent-url:9000
# fly secrets set SECURITY_AGENT_TOKEN=your-token
