# fly.toml app configuration file generated for free-a--lma-silent-pine-5957 on 2025-10-19T23:06:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'free-a--lma-silent-pine-5957'
primary_region = 'sin'

[build]

[env]
  APP_PORT = '3000'
  DB_TYPE = 'postgres'
  DB_HOST = 'ahexnoaazbveiyhplfrc.supabase.co'
  DB_PORT = '5432'
  DB_NAME = 'postgres'
  DB_USER = 'postgres'
  DB_LOGGING = 'false'
  DB_SYNC = 'false'
  FS_ESL_PORT = '8021'
  NODE_ENV = 'production'
  RECORDINGS_DIR = '/recordings'
  SECURITY_AGENT_TIMEOUT_MS = '3000'
  SEED_DEMO_DATA = 'false'
  TZ = 'Asia/Kuala_Lumpur'
  SUPABASE_URL = 'https://ahexnoaazbveiyhplfrc.supabase.co'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
